# Generated by Django 3.0.9 on 2020-08-08 15:01

import classroom.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingMaterials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=50, verbose_name='Sekolah')),
                ('grade', models.CharField(max_length=50, verbose_name='Tingkat kelas')),
                ('subject', models.CharField(max_length=50, verbose_name='Mata Pelajaran')),
                ('topic', models.CharField(max_length=50, verbose_name='Topik')),
            ],
        ),
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docs', models.FileField(upload_to=classroom.models.group_based_upload_to)),
                ('teaching_materials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='classroom.TeachingMaterials')),
            ],
        ),
    ]
