version: '3.5'
    
services:
  db:
    image: postgres:12.3-alpine
    restart: always
    env_file: ../.envs/.local/.postgres
    ports:
      - "5432:5432"

  redis:
    image: "redis:6.0-alpine"
    restart: always
    ports:
    - "6379:6379"